spring:
  application:
    name: guaranteeRateService
  datasource:
    url: jdbc:postgresql://localhost:5432/guaranteeRateDB
    username: postgres
    password: Anurodh@1708
  jpa:
    hibernate:
      ddl-auto: update
